---
title: 'EKN-812: Problem Set 1'
author:
date: 
output: pdf_document
bibliography: /Users/jnaidoo/Dropbox/office/library.bib
biblio-style: authordate1
geometry: margin=1in
---

_There are 95 points available on this problems set. It will be graded out of 80 (i.e. there are 15 bonus points available)._

**Due Date: February 21, 2019**

1. Find the Marshallian and Hicksian demands for the following preferences. Compute the Marshallian (own-price) elasticity of demand for good $x$. Use $m$ for the agent's income, $p_x$ for the price of $x$, and $p_y$ for the price of $y$.
    (a) quasilinear utility: let $\varepsilon > 0$ be some constant, and let
    $$
    u(x, y) = y + \frac{x^{1-\varepsilon^{-1}}}{1-\varepsilon^{-1}}
    $$
    (b) CES utility with two goods: let $-\infty < \rho \leq 1$ and $\alpha \in (0,1)$ be given constants, and let
    $$
    u(x,y) = \left(\alpha x^\rho + (1-\alpha) y^\rho\right)^{1/\rho}
    $$
    (c) quadratic utility: let $\overline{x}, \overline{y} > 0$ be given constants; also let $a, b$ be known with $a > 0$. Consider
    $$
    u(x,y) = -\frac{1}{2}\left(a(\overline{x} - x)^2 + 2b(\overline{x} - x)(\overline{y} - y)+ (\overline{y} - y)^2\right)
    $$
    What restrictions do you need to ensure that $u(x,y)$ is concave? Given the "bliss point" $(\overline{x}, \overline{y})$, what restrictions do you need to impose on $(p_x, p_y, m)$ to ensure that the solution to the consumer's problem is interior? 

\hfill [$3 \times 10 = 30$ points]

2. Let $\varepsilon > 0$ be given and let
    $$
    u(x, y) = \frac{x^{1 - \varepsilon^{-1}}}{1 - \varepsilon^{-1}} + \frac{y^{1 - (2\varepsilon)^{-1}}}{1 - (2\varepsilon)^{-1}}
    $$
    Find the Marshallian demands generated by these preferences. Are they homothetic? Which good is a relative "luxury", and which is a relative "necessity"? How would you compute the Hicksian demands? Hint: you may find it easiest to solve for the marginal utility of income first.

\hfill [10 points]

3. In class I claimed that in a two-good demand system, the goods have to be substitutes. Prove this claim.

\hfill [5 points]

4. Suppose, as in class, that consumers do not maximize utility but passively consume whatever is feasible. In particular, assume that each consumer has a "type" $k$ such that he always spends a fraction $k$ on good $x$, and exhausts his budget. Assume $k$ is uniformly distributed on the unit interval $[0,1]$.
   (a) If all consumers have the same income $m$, what bundle does a consumer of type $k$ choose?
   (b) Given the prices $p_x$ and $p_y$, what is the market average consumption of $x$? Of $y$?
   (c) Now suppose the price of $x$ rises to $p'_x$, but consumers are compensated such that the market average bundle is still affordable. Compute the market consumption of $x$ after this change.
   (d) What is the elasticity of market demand?

\hfill [$4 \times 2 = 8$ points]

5. A consumer buys light bulbs only because she likes light. A new light bulb is invented which lasts twice as long as the old bulbs but costs the same. In the long run (when all her old bulbs have burned out), will her demand for bulbs rise or fall?

\hfill [12 points]

6. Consider a welfare program in which a set of people are all given identical houses. Suppose each of the recipients did not have a house before (perhaps they had just moved from living in a different city, or lived with friends or family before). There is also a private market on which housing sells at a unit price of $p$. Here, you can think of "more" housing as being higher quality, or literally a larger home. However, there is also a cost $c < p$ associated with selling these houses; think of $c$ as representing lawyer's fees, or the time and inconvenience of going to the deeds office to transfer ownership to a buyer.

We then observe that some recipients sold the houses and kept the money (or used it for other things besides housing). Some of them sell their free houses and then buy ones of lower quality. Some of them sell their free houses and buy ones of even higher quality. Finally, some of the recipients just stay in the houses they were given.

(a) Illustrate the budget set facing a beneficiary of this free housing program.
(b) Can we infer that any, all, or none of these different groups of people would have preferred to have been given the cash value of the houses?
(c) Suppose that the list of beneficiaries was announced before the houses were actually built and handed over, but it was legal to sell your place on the list to someone else. Can you place upper or lower bounds on the price that the beneficiaries would be willing to accept in order to sell their place on the list?
(d) Can you rank the different groups by how much they value their place on the list?

\hfill [$4 \times 5 = 20$ points]

7. Does rationing make _Marshallian_ demands less price-elastic? Provide a proof or counterexample.

\hfill [10 points]
